import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import NextTopLoader from "nextjs-toploader";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from '@vercel/speed-insights/next';

// Initialize the Inter font
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the page
export const metadata: Metadata = {
	title: "Attendance App",
	description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// "suppressHydrationWarning" is used to hide app-index.js:35 Warning: Extra attributes from the server: class
		<html lang="en" suppressHydrationWarning>
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
					integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"
				/>
			</head>
			<body className={inter.className}>
				<NextTopLoader
					height={2}
					color="#27AE60"
					easing="cubic-bezier(0.53,0.21,0,1)"
					showSpinner={false}
				/>
				<ContextProvider>
					<GlobalStyleProvider>
						<div className="w-full">{children}</div>
						<Analytics />
						<SpeedInsights />
					</GlobalStyleProvider>
				</ContextProvider>
			</body>
		</html>
	);
}
